version: "3"
services:
  app:
    container_name: "mys3"
    env_file: .env.dev
    build: .
    depends_on:
      - postgres
    ports:
      - "1337:1337"
      - "8181:8181"
    volumes:
      - /home/app/mys3-server
      - /home/app/mys3-client
      - /home/app/node_modules
    environment:
      DB_HOST: 172.28.1.2
    networks:
      mys3:
        ipv4_address: 172.28.1.1

  postgres:
    container_name: "psql"
    image: postgres:11
    environment:
      POSTGRES_USER: mys3
      POSTGRES_PASSWORD: mys3
      POSTGRES_DB: mys3
    #volumes:
    #  - ./docker/initdb.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      mys3:
        ipv4_address: 172.28.1.2

networks:
  mys3:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
