version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "1337:1337"
      - "8181:8181"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - ./docker/initdb.sql
    environment:
      POSTGRES_PASSWORD: postgres
