version: "3"
services:
  app:
    container_name: "mys3"
    env_file: .env.dev
    volumes:
      - .:/home/app/mys3-server
      - .:/home/app/mys3-client
      - /home/app/node_modules
    environment:
      DB_HOST: 172.28.1.1
    networks:
      mys3:
        ipv4_address: 172.28.1.3

networks:
  mys3:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
